const entities = {
  quests: {
    byId: {
      quest0: {
        id: "quest0",
        title: "Петропавловская Крепость и Окрестности",
        cover:
          "https://kudago.com/media/images/news/d3/2e/d32ecc1b3e4aa49f49c5f220a8dc88b8.jpg",
        desc: "Как всё хорошо и замечательно в этом квесте. У всех безудержное веселье, все добрые и всех любят, в воздухе летают бабочки, вокруг бегают единороги и блюют радугой! Нет больше бедности и болезней, все получили премию. Отменили санкции и вообще теперь счастье всей планете. Всего за 500 рублей",
        questionsInOrder: ["question0", "question1", "question2"],
      },
      quest1: {
        id: "quest1",
        title: "Прогулка в Торговый Центр",
        cover:
          "http://megapixeli.pro/wp-content/uploads/2017/02/20170131-DJI_0589-1621x1080.jpg",
        desc: "Как всё хорошо и замечательно в этом квесте. У всех безудержное веселье, все добрые и всех любят, в воздухе летают бабочки, вокруг бегают единороги и блюют радугой! Нет больше бедности и болезней, все получили премию. Отменили санкции и вообще теперь счастье всей планете. Всего за 500 рублей",
        questionsInOrder: [
          "question3",
          "question4",
          "question5",
          "question6",
          "question7",
          "question8",
          "question9",
          "question10",
          "question11",
          "question12",
          "question13",
          "question14",
          "question15",
          "question16",
          "question17",
        ],
      },
    },
    allIds: ["quest0", "quest1"],
  },
  questions: {
    byId: {
      question0: {
        id: "question0",
        quest: "quest0",
        media: {
          type: "image",
          uri: "https://kudago.com/media/images/news/d3/2e/d32ecc1b3e4aa49f49c5f220a8dc88b8.jpg",
        },
        desc: "На этом месте будет описание вопроса и рассказ о том, как это важно и как интересно и что и когда и кто и зачемНа этом месте будет описание вопроса и рассказ о том, как это важно и как интересно и что и когда и кто и зачем",
        questionText: "Сколько планет в солнечной системе?",
        answer: "8",
        answerDesc: "Потому что Плутон больше не планета",
      },
      question1: {
        id: "question1",
        quest: "quest0",
        media: {
          type: "image",
          uri: "https://d3hdm9bjz45yxn.cloudfront.net/userfiles/excursiongalleries/pictureshd/345/4129.jpeg",
        },
        desc: "На этом месте будет описание вопроса и рассказ о том, как это важно и как интересно и что и когда и кто и зачемНа этом месте будет описание вопроса и рассказ о том, как это важно и как интересно и что и когда и кто и зачем",
        questionText: "Сколько часов в сутках?",
        answer: "24",
        answerDesc: "Хотелось бы больше, конечно",
      },
      question2: {
        id: "question2",
        quest: "quest0",
        media: {
          type: "image",
          uri: "http://estelhautecouture.ru/assets/i/upload/20150401/dfa173b463af881eade974a743ac8929.jpg",
        },
        desc: "На этом месте будет описание вопроса и рассказ о том, как это важно и как интересно и что и когда и кто и зачемНа этом месте будет описание вопроса и рассказ о том, как это важно и как интересно и что и когда и кто и зачем",
        questionText: "Сколько дней в неделе?",
        answer: "7",
        answerDesc: "Нужно больше дней в неделе",
      },
      question3: {
        id: "question3",
        quest: "quest1",
        media: {
          type: "image",
          uri: "https://kudago.com/media/images/news/d3/2e/d32ecc1b3e4aa49f49c5f220a8dc88b8.jpg",
        },
        desc: "Василий, выходите из дома. На улице: *ссыль на погоду (давай пока с погодой не будем ничего делать)*. Настало время для квеста.",
        questionText: "Вы вышли из дома?",
        answer: "Да",
        answerDesc: "Потому что чтобы пройти квест надо выйти из дома",
      },
      question4: {
        id: "question4",
        quest: "quest1",
        media: {
          type: "image",
          uri: "https://d3hdm9bjz45yxn.cloudfront.net/userfiles/excursiongalleries/pictureshd/345/4129.jpeg",
        },
        desc: "Чудесный денек, чтобы прогуляться вдоль по Съезжинской улице до парка. Будьте осторожны! Не сверните случайно на Татарский переулок! Там может быть опасно…",
        questionText:
          "Проходя мимо развилки, обратите внимание на фасад здания: сколько колонн?",
        answer: "6",
        answerDesc: "Нужны пояснения к ответам на вопросы",
      },
      question5: {
        id: "question5",
        quest: "quest1",
        media: {
          type: "image",
          uri: "http://estelhautecouture.ru/assets/i/upload/20150401/dfa173b463af881eade974a743ac8929.jpg",
        },
        desc: "Найдите по пути этот символ",
        questionText: "На двери какого заведения он?",
        answer: "Кофейня",
        answerDesc: "",
      },
      question6: {
        id: "question6",
        quest: "quest1",
        media: {
          type: "image",
          uri: "http://estelhautecouture.ru/assets/i/upload/20150401/dfa173b463af881eade974a743ac8929.jpg",
        },
        desc: "Найдите по пути этот символ",
        questionText: "На двери какого заведения он?",
        answer: "Кофейня",
        answerDesc: "",
      },
      question7: {
        id: "question7",
        quest: "quest1",
        media: {
          type: "image",
          uri: "http://estelhautecouture.ru/assets/i/upload/20150401/dfa173b463af881eade974a743ac8929.jpg",
        },
        desc: "Зайдите внутрь, возьмите чего-нибудь бодрящего и вперед к приключениям!  Найдите ближайший светофор (он будет на перекрестке введенской и кронверкского) .k Переходите дорогу по правилам. Пройдите в парк прямо, до пустыря окруженного скамейками и с камнем по центру. Посмотрите на камень со всех сторон.",
        questionText:
          "Внимание, вопрос: когда здесь будет установлен памятник?",
        answer: "никогда",
        answerDesc: "да вы, гляжу, пессимист, батенька. Но это не страшно!",
      },
      question8: {
        id: "question8",
        quest: "quest1",
        media: {
          type: "image",
          uri: "http://estelhautecouture.ru/assets/i/upload/20150401/dfa173b463af881eade974a743ac8929.jpg",
        },
        desc: "Прогуляйтесь по парку, посмотрите на здание бывшего казино, приглядитесь к зданию ИТМО через дорогу. По правую руку от вас будет мюзикхолл , а рядом с ним планетарий и выставка восковых фигур.",
        questionText: "Кстати, какая фигура сейчас стоит у входа на выставку?",
        answer: "Динозавр",
        answerDesc: "",
      },
      question9: {
        id: "question9",
        quest: "quest1",
        media: {
          type: "image",
          uri: "http://estelhautecouture.ru/assets/i/upload/20150401/dfa173b463af881eade974a743ac8929.jpg",
        },
        desc: "Мы и не подозревали! Идем дальше? Проходим мимо театра Балтийский дом, Великан-Парка. Идем-идем, нам еще гулять и гулять! Ищем взглядом летающую тарелку. Как не бывает? Здесь все бывает. Нашли?",
        questionText: "Что внутри летающей тарелки?",
        answer: "Метро",
        answerDesc: "",
      },
      question10: {
        id: "question10",
        quest: "quest1",
        media: {
          type: "image",
          uri: "http://www.metallostroy.org/new/gallery/album_96/med_gallery_2_96_125600.jpg",
        },
        desc: "но мы туда не пойдем. Углубляемся в парк. Если присмотреться, здесь есть различные скульптуры. Найдите эту:",
        questionText: "Что она держит в руках?",
        answer: "Голубь",
        answerDesc: "",
      },
      question11: {
        id: "question11",
        quest: "quest1",
        media: {
          type: "image",
          uri: "http://estelhautecouture.ru/assets/i/upload/20150401/dfa173b463af881eade974a743ac8929.jpg",
        },
        desc: "Идите сюда",
        questionText: "Кстати, как фамилия той Матильды, чей это был дом?",
        answer: "Кшесинская",
        answerDesc: "",
      },
      question12: {
        id: "question12",
        quest: "quest1",
        media: {
          type: "image",
          uri: "http://estelhautecouture.ru/assets/i/upload/20150401/dfa173b463af881eade974a743ac8929.jpg",
        },
        desc: "Идите прямо по улице куйбышева (ff раньше эта улица называлась Большая Дворянская), пока не выйдите на петроградскую набережную, перейдите дорогу – вы не на набережной, пока не подойдете поближе к воде. Проходя мимо памятнику Нобелю, присмотритесь",
        questionText: "что  изобразил автор?",
        answer: "дерево",
        answerDesc: "",
      },
      question13: {
        id: "question13",
        quest: "quest1",
        media: {
          type: "image",
          uri: "http://estelhautecouture.ru/assets/i/upload/20150401/dfa173b463af881eade974a743ac8929.jpg",
        },
        desc: "Идите дальше по набережной, пока не дойдете до первого пришвартованного судна желто-зеленого цвета.",
        questionText: "Как оно называется? ",
        answer: "Забава бар",
        answerDesc: "",
      },
      question14: {
        id: "question14",
        quest: "quest1",
        media: {
          type: "image",
          uri: "http://estelhautecouture.ru/assets/i/upload/20150401/dfa173b463af881eade974a743ac8929.jpg",
        },
        desc: "Переходим дорогу  (помните про пдд)– нам необходимо добраться до аптекарской набережной.",
        questionText: "Кстати, как называется сад вначале набережной?",
        answer: "ботанический",
        answerDesc: "",
      },
      question15: {
        id: "question15",
        quest: "quest1",
        media: {
          type: "image",
          uri: "http://estelhautecouture.ru/assets/i/upload/20150401/dfa173b463af881eade974a743ac8929.jpg",
        },
        desc: "проходим сад. Нужно найти большое парадное здание желтого цвета с колоннами",
        questionText: "Что за компания в здании?",
        answer: "Лукойл",
        answerDesc: "",
      },
      question16: {
        id: "question16",
        quest: "quest1",
        media: {
          type: "image",
          uri: "http://estelhautecouture.ru/assets/i/upload/20150401/dfa173b463af881eade974a743ac8929.jpg",
        },
        desc: "Каждая сфотографированная и выложенная в инстаграмм бутылка на набережной дает вам плюсик в карму.",
        questionText: "Ok?",
        answer: "Ok",
        answerDesc: "",
      },
      question17: {
        id: "question17",
        quest: "quest1",
        media: {
          type: "image",
          uri: "http://estelhautecouture.ru/assets/i/upload/20150401/dfa173b463af881eade974a743ac8929.jpg",
        },
        desc: "",
        questionText:
          "машины с какой мах высотой могут проезжать под кантимировским мостом?",
        answer: "4,8",
        answerDesc:
          "вы заслужили отдых! Зайдите в торговый центр, выпейте чашечку чая в КХ. Обсудите квест",
      },
    },
    allIds: [
      "question0",
      "question1",
      "question2",
      "question3",
      "question4",
      "question5",
      "question6",
      "question7",
      "question8",
      "question9",
      "question10",
      "question11",
      "question12",
      "question13",
      "question14",
      "question15",
      "question16",
      "question17",
    ],
  },
};

export default {
  entities,
  progress: {},
};
