export default {
  START_QUEST: 'START_QUEST',
  ANSWER_QUESTION: 'ANSWER_QUESTION',
  SHOW_CORRECT_ANSWER: 'SHOW_CORRECT_ANSWER',
  GOTO_NEXT_QUESTION: 'GOTO_NEXT_QUESTION',
  RESTART_QUEST: 'RESTART_QUEST',

  UPDATE_QUEST_LIST: 'UPDATE_QUEST_LIST',

  DOWNLOADING_QUEST_START: 'DOWNLOADING_QUEST_START',
  DOWNLOADING_QUEST_SUCCESS: 'DOWNLOADING_QUEST_SUCCESS',

  LOGIN_START: 'LOGIN_START',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT: 'LOGOUT',

  SHOW_LOGIN_MODAL: 'SHOW_LOGIN_MODAL',
  HIDE_LOGIN_MODAL: 'HIDE_LOGIN_MODAL',

  SYNC_PROGRESS_SUCCESS: 'SYNC_PROGRESS_SUCCESS',

  DELETE_QUEST: 'DELETE_QUEST'
};
